
#########################################################################################################################################################
[Pathway]

[Pathway.observations-dir]

ground_observation_data_dir                           = '/my-projects/Projects/PM25_Speices_DL_2023/data/monthly_observation/' 
geophysical_species_data_dir                          = '/my-projects/Projects/PM25_Speices_DL_2023/data/monthly_geophysical/'
geophysical_biases_data_dir                           = '/my-projects/Projects/PM25_Speices_DL_2023/data/monthly_biases/'
ground_observation_data_infile                        = '{}_monthly_observations.nc'
geophysical_species_data_infile                       = '{}_monthly_geophysical_concentration.nc'
geophysical_biases_data_infile                        = '{}_monthly_biases_concentration.nc'

[Pathway.TrainingModule-dir]

training_infile                                       = '/my-projects/Projects/PM25_Speices_DL_2023/data/TrainingDatasets/{}/{}-cnn_TrainingData_56channels_11x11_200001-201912.nc'
model_outdir                                          = '/my-projects/Projects/PM25_Speices_DL_2023/code/Training_Evaluation_Estimation/'

[Pathway.Results-dir]

txt_outdir                                            = '/my-projects/Projects/PM25_Speices_DL_2023/code/Training_Evaluation_Estimation/'

[Pathway.Config-outdir]

Config_outdir                                         = '/my-projects/Projects/PM25_Speices_DL_2023/code/Training_Evaluation_Estimation/'

[Pathway.Figures-dir]

Loss_Accuracy_outdir                                  = '/my-projects/Projects/PM25_Speices_DL_2023/code/Training_Evaluation_Estimation/'
Estimation_Map_outdir                                 = '/my-projects/Projects/PM25_Speices_DL_2023/code/Training_Evaluation_Estimation/'
Uncertainty_Map_outdir                                = '/my-projects/Projects/PM25_Speices_DL_2023/code/Training_Evaluation_Estimation/'

[Pathway.Estimation-dir]

Estimation_outdir                                     = '/my-projects/Projects/PM25_Speices_DL_2023/code/Training_Evaluation_Estimation/'
Uncertainty_outdir                                    = '/my-projects/Projects/PM25_Speices_DL_2023/code/Training_Evaluation_Estimation/'
#########################################################################################################################################################

[Spatial-CrossValidation]

Spatial_CrossValidation_Switch                        = true
Spatial_CV_LossAccuracy_plot_Switch                   = true

[Spatial-CrossValidation.Training_Settings]

kfold                                                 = 10
repeats                                               = 1
beginyears                                            = [2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019]
endyears                                              = [2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019]
test_beginyear                                        = 2000
test_endyear                                          = 2019

[Spatial-CrossValidation.Visualization_Settings]

regression_plot_switch                                = true

[Spatial-CrossValidation.Forced-Slope-Unity]

ForcedSlopeUnity                                      = false # True: force the slope to unity and offset to zero with Training datasets
EachMonthForcedSlopeUnity                             = true # True: force the slope to unity and offset to zero by each year, each month; False: by each month, but all-year average 

#########################################################################################################################################################

[BLOO-CrossValidation]

BLOO_CrossValidation_Switch                           = false
Buffer_size                                           = [0,10,20,30,40,50,60,70,80,90,100,110,120,130,140,150,160,170,180,190,200]

[BLOO-CrossValidation.TrainingSettings]

kfold                                                 = 10
repeats                                               = 1
beginyears                                            = [2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019]
endyears                                              = [2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019]
test_beginyear                                        = 2001
test_endyear                                          = 2019


#########################################################################################################################################################

[FixNumber-SpatialCrossValidation]

FixNumber_CrossValidation_Switch                      = false

[FixNumber-SpatialCrossValidation.TrainingSettings]

kfold                                                 = 30
repeats                                               = 1
beginyears                                            = [2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019]
endyears                                              = [2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019]
test_beginyear                                        = 2001
test_endyear                                          = 2019
fixednumber_test_sites                                = []
fixednumber_train_sites                               = []



#########################################################################################################################################################

[Estimation-Settings]

Estimation_Switch                                     = false
Train_model_Switch                                    = false
Map_estimation_Switch                                 = false
Estimation_visualization_Switch                       = false
Derive_combinedGeo_MapData_Switch                     = false

[Estimation-Settings.Training_Settings]

beginyears                                            = [2018]#[2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019]
endyears                                              = [2018]#[2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019]

[Estimation-Settings.Map_Estimation_Settings]

Estiamtion_trained_beginyears                         = [2018]
Estiamtion_trained_endyears                           = [2018]
Estimation_years                                      = [[2018]]#[[2001],[2002],[2003],[2004],[2005],[2006],[2007],[2008],[2009],[2010],[2011],[2012],[2013],[2014],[2015],[2016],[2017],[2018],[2019]]
Estiamtion_months                                     = [0,1,2,3,4,5,6,7,8,9,10,11]
Extent                                                = [10.055,69.945,-169.945,-40.055]

[Estimation-Settings.Visualization_Settings]

Map_Plot_Switch                                       = true       # Switch for plotting the map of estimated concentration. 
Map_Plot_YEARS                                        = [2018]#[2011,2012,2013,2014,2015,2016,2017,2018,2019]#[2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019]
Map_Plot_MONTHS                                       = ['01','02','03','04','05','06','07','08','09','10','11','12']
Map_Plot_Area                                         = 'NA'
Map_Plot_Extent                                       = [10.055,69.945,-169.945,-50.055]

[Estimation-Settings.CombineWithGeophysical_Settings]

Coefficient_start_distance                            = 130

#########################################################################################################################################################

[Uncertainty-Settings]

Uncertainty_Switch                                    = false
Derive_distances_map_Switch                           = false
Derive_rRMSE_map_Switch                               = false
Derive_absolute_Uncertainty_map_Switch                = false
Uncertainty_visualization_Switch                      = false

[Uncertainty-Settings.Map_Estimation_Settings]

Estimation_years                                      = [2011,2012,2013,2014,2015,2016,2017]#,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019]
Estiamtion_months                                     = ['01','02','03','04','05','06','07','08','09','10','11','12']
Buffer_radii_forUncertainty                           = [0,10,20,30,40,50,60,70,80,90,100,110,120,130,140,150,160,170,180,190,200]

[Uncertainty-Settings.Visualization_Settings]

Uncertainty_Plot_Switch                               = true       # Switch for plotting the map of estimated concentration. 
Uncertainty_Plot_YEARS                                = [2011,2012,2013,2014,2015,2016,2017]#,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019]
Uncertainty_Plot_Extent                               = [10.055,69.945,-169.945,-50.055]
Uncertainty_Plot_MONTHS                               = ['01','02','03','04','05','06','07','08','09','10','11','12']
Uncertainty_Plot_Area                                 = 'NA'




#########################################################################################################################################################
[Training-Settings]

[Training-Settings.identity]

version                                               = 'v1.2.1'
special_name                                          = '_Exclude-Global_CNN'

[Training-Settings.learning-objective]

species                                               = 'PM25' # ['PM25', 'NH4', 'SO4', 'NO3', 'OM', 'BC', 'DUST', 'SS' ]

# Only one of these can be true. Default is bias.
bias                                                  = true   # learning objectives: bias = ground-based species observation - geophysical species concentration estimation
normalize_bias                                        = false
normalize_species                                     = false
absolute_species                                      = false 
log_species                                           = false


[Training-Settings.net_structure_settings]

ResNet.Settings                                       = false
ResNet.Blocks                                         = 'BasicBlock'
ResNet.blocks_num                                     = [1,1,1,1]
#############
LateFusion.Settings                                   = true
LateFusion.Blocks                                     = 'BasicBlock'
LateFusion.blocks_num                                 = [1,1,1,1]
LateFusion.initial_channels                           = ['EtaAOD_Bias', 'EtaCoastal', 'EtaMixing', 'EtaSGAOD_Bias', 'EtaSGTOPO_Bias', 'AOD', 'ETA', 'GeoPM25',
                                                        #'GeoNH4','GeoNIT','GeoSO4','GeoBC','GeoOM','GeoDUST','GeoSS',
                                                       #'GL_CNN_PM25',#'NA_CNN_PM25',#
                                                       'GC_PM25', 'GC_NH4', 'GC_SO4', 'GC_NIT', 'GC_SOA', 'GC_OC', 'GC_OM', 'GC_BC', 'GC_DST','GC_SSLT',
                                                        'NH3_anthro_emi','SO2_anthro_emi', 'NO_anthro_emi', 'OC_anthro_emi', 'BC_anthro_emi',  #'N2O_anthro_emi','NMVOC_anthro_emi',
                                                       'DST_offline_emi', 'SSLT_offline_emi',
                                                       'PBLH', 'RH', 'T2M', 'U10M', 'V10M',#'PRECTOT',
                                                       'Urban_Builtup_Lands',# 'Croplands',#'Crop_Nat_Vege_Mos', 'Permanent_Wetlands', 'Croplands', 
                                                       #,#'S1','S2','S3',' 
                                                        #'Population'
                                                       ] 
LateFusion.LateFusion_channels                         = ['Lat', 'Lon','Month_of_Year',#'elevation',
                                                          ]
#############
MultiHeadLateFusion.Settings                           = false
MultiHeadLateFusion.Blocks                             = 'BasicBlock'
MultiHeadLateFusion.blocks_num                         = [1,1,1,1]
MultiHeadLateFusion.initial_channels                   = ['EtaAOD_Bias', 'EtaCoastal', 'EtaMixing', 'EtaSGAOD_Bias', 'EtaSGTOPO_Bias', 'AOD', 'ETA', 'GeoPM25',
                                                        'GeoNH4','GeoNIT','GeoSO4','GeoBC','GeoOM','GeoDUST','GeoSS',
                                                        'NA_CNN_PM25',#'GL_CNN_PM25'
                                                        'GC_PM25', 'GC_NH4', 'GC_SO4', 'GC_NIT', 'GC_SOA', 'GC_OC', 'GC_OM', 'GC_BC', 'GC_DST','GC_SSLT',
                                                        'NH3_anthro_emi','SO2_anthro_emi', 'NO_anthro_emi',#'OC_anthro_emi', 'BC_anthro_emi',  # 'N2O_anthro_emi','NMVOC_anthro_emi',
                                                        'DST_offline_emi', 'SSLT_offline_emi',
                                                        'PBLH', 'RH', 'T2M', 'U10M', 'V10M',#'PRECTOT',
                                                        'Urban_Builtup_Lands',# 'Croplands',#'Crop_Nat_Vege_Mos', 'Permanent_Wetlands', 'Croplands', 
                                                       #,#'S1','S2','S3',' 
                                                        #'Population'
                                                       ] 
MultiHeadLateFusion.LateFusion_channels                = ['Lat', 'Lon','elevation','Month_of_Year']
MultiHeadLateFusion.left_bin                           = -10.0
MultiHeadLateFusion.right_bin                          = 10.0
MultiHeadLateFusion.bins_number                        = 201
MultiHeadLateFusion.regression_portion                 = 0.5
MultiHeadLateFusion.classifcation_portion              = 0.5

[Training-Settings.optimizer]

Adam.Settings                                         = true
Adam.beta0                                            = 0.9
Adam.beta1                                            = 0.999
Adam.eps                                              = 1e-8


[Training-Settings.learning_rate]

learning_rate0                                        = 0.01

ExponentialLR.Settings                                = false
ExponentialLR.gamma                                   = 0.9

CosineAnnealingLR.Settings                            = true
CosineAnnealingLR.T_max                               = 10
CosineAnnealingLR.eta_min                             = 0.0001

CosineAnnealingRestartsLR.Settings                    = false
CosineAnnealingRestartsLR.T_0                         = 10
CosineAnnealingRestartsLR.T_mult                      = 2
CosineAnnealingRestartsLR.eta_min                     = 0

[Training_Settings.activation_func]

activation_func_name                                  = 'relu'
ReLU.Settings                                         = false
Tanh.Settings                                         = false
GeLU.Settings                                         = true
Sigmoid.Settings                                      = false


[Training-Settings.hyper-parameters]

epoch                                                 = 30
batchsize                                             = 128

channel_names                                         = ['EtaAOD_Bias', 'EtaCoastal', 'EtaMixing', 'EtaSGAOD_Bias', 'EtaSGTOPO_Bias', 'AOD', 'ETA', 'GeoPM25',
                                                       #'GeoNH4','GeoNIT','GeoSO4','GeoBC','GeoOM','GeoDUST','GeoSS',
                                                       #'GL_CNN_PM25',#'NA_CNN_PM25',#
                                                       'GC_PM25', 'GC_NH4', 'GC_SO4', 'GC_NIT', 'GC_SOA', 'GC_OC', 'GC_OM', 'GC_BC', 'GC_DST','GC_SSLT',
                                                       'NH3_anthro_emi','SO2_anthro_emi', 'NO_anthro_emi',  'OC_anthro_emi', 'BC_anthro_emi',  #'N2O_anthro_emi','NMVOC_anthro_emi',
                                                       'DST_offline_emi', 'SSLT_offline_emi',
                                                       'PBLH', 'RH', 'T2M', 'U10M', 'V10M',#'PRECTOT',
                                                       'Urban_Builtup_Lands',# 'Croplands','Crop_Nat_Vege_Mos', 'Permanent_Wetlands', 'Croplands', 
                                                       'Month_of_Year',
                                                       'Lat', 'Lon',#'elevation'#'S1','S2','S3',
                                                        #'Population'
                                                       ] 

Addtional_LogVariables_Settings                       = false
Addtional_LogVariables                                = ['GC_PM25', 'GC_NH4', 'GC_SO4', 'GC_NIT', 'GC_SOA', 'GC_OC', 'GC_OM', 'GC_BC', 'GC_DST','GC_SSLT']

GeoSpecies_Ratio_Settings                             = false
GeoSpecies_Ratio_variables                            = ['GeoNH4','GeoNIT','GeoSO4','GeoBC','GeoOM','GeoDUST','GeoSS']

Global_GeoSpecies_Settings                            = false
Global_GeoSpecies_variables                           = ['GeoNH4','GeoNIT','GeoSO4','GeoBC','GeoOM','GeoDUST','GeoSS']

[Training-Settings.Loss-Functions]

Loss_type                                             = 'MSE'
Classification_loss_type                              = 'CrossEntropyLoss'

[Training-Settings.CombineWithGeophysical]

combine_with_GeophysicalSpeceis_Switch                = false
cutoff_size                                           = 130


