
#########################################################################################################################################################
[Pathway]

[Pathway.observations-dir]

ground_observation_data_dir                           = '/my-projects/Projects/PM25_Speices_DL_2023/data/monthly_observation/' 
geophysical_species_data_dir                          = '/my-projects/Projects/PM25_Speices_DL_2023/data/monthly_geophysical/'
geophysical_biases_data_dir                           = '/my-projects/Projects/PM25_Speices_DL_2023/data/monthly_biases/'

[Pathway.TrainingModule-dir]

training_infile                                       = '/my-projects/Projects/PM25_Speices_DL_2023/data/TraningDatasets/PM25/PM25-cnn_TrainingData_44channels_11x11_200001-201912.nc'
model_outdir                                          = '/my-projects/Projects/PM25_Speices_DL_2023/code/Training_Evaluation_Estimation/'

[Pathway.Results-dir]

txt_outdir                                            = '/my-projects/Projects/PM25_Speices_DL_2023/code/Training_Evaluation_Estimation/'

[Pathway.Config-outdir]

Config_outdir                                         = '/my-projects/Projects/PM25_Speices_DL_2023/code/Training_Evaluation_Estimation/'

[Pathway.Figures-dir]

Loss_Accuracy_outdir                                  = '/my-projects/Projects/PM25_Speices_DL_2023/code/Training_Evaluation_Estimation/'

#########################################################################################################################################################

[Spatial-CrossValidation]

Spatial_CrossValidation_Switch                        = true
Spatial_CV_LossAccuracy_plot_Switch                   = true

[Spatial-CrossValidation.Training_Settings]

kfold                                                 = 10
repeats                                               = 1
beginyears                                            = [2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019]
endyears                                              = [2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019]
test_beginyear                                        = 2001
test_endyear                                          = 2019

[Spatial-CrossValidation.Visualization_Settings]

regression_plot_switch                                = true

[Spatial-CrossValidation.Forced-Slope-Unity]

ForcedSlopeUnity                                      = false # True: force the slope to unity and offset to zero with Training datasets
EachMonthForcedSlopeUnity                             = true # True: force the slope to unity and offset to zero by each year, each month; False: by each month, but all-year average 

#########################################################################################################################################################

[BLOO-CrossValidation]

BLOO_CrossValidation_Switch                           = false
Buffer_size                                           = 0

[BLOO-CrossValidation.TrainingSettings]

kfold                                                 = 10
repeats                                               = 1
beginyears                                            = [2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019]
endyears                                              = [2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019]
test_beginyear                                        = 2001
test_endyear                                          = 2019



#########################################################################################################################################################
[Training-Settings]

[Training-Settings.identity]

version                                               = 'v1.0.0'
special_name                                          = '_ResNet_Basic1111_1'

[Training-Settings.learning-objective]

species                                               = 'PM25' # ['PM25', 'NH4', 'SO4', 'NO3', 'OM', 'BC', 'DUST', 'SS' ]

# Only one of these can be true. Default is bias.
bias                                                  = true   # learning objectives: bias = ground-based species observation - geophysical species concentration estimation
normalize_bias                                        = false
normalize_species                                     = false
absolute_species                                      = false 
log_species                                           = false


[Training-Settings.net_structure_settings]

ResNet.Settings                                       = true
ResNet.Blocks                                         = 'BasicBlock'
ResNet.blocks_num                                     = [1,1,1,1]
[Training-Settings.learning_rate]

learning_rate0                                        = 0.01

ExponentialLR.Settings                                = false
ExponentialLR.gamma                                   = 0.9

CosineAnnealingLR.Settings                            = true
CosineAnnealingLR.T_max                               = 10
CosineAnnealingLR.eta_min                             = 1e-4

CosineAnnealingRestartsLR.Settings                    = false
CosineAnnealingRestartsLR.T_0                         = 10
CosineAnnealingRestartsLR.T_mult                      = 2
CosineAnnealingRestartsLR.eta_min                     = 0

[Training_Settings.activation_func]

activation_func_name                                  = 'relu'
ReLU.Settings                                         = false
Tanh.Settings                                         = false
GeLU.Settings                                         = true


[Training-Settings.hyper-parameters]

epoch                                                 = 70
batchsize                                             = 128

channel_names                                         = ['EtaAOD_Bias', 'EtaCoastal', 'EtaMixing', 'EtaSGAOD_Bias', 'EtaSGTOPO_Bias', 'AOD', 'ETA', 'GeoPM25',
                                                       'GL_CNN_PM25',
                                                       'GC_PM25', 'GC_NH4', 'GC_SO4', 'GC_NIT', 'GC_SOA', 'GC_OC', 'GC_OM', 'GC_BC', 'GC_DST', 'GC_SSLT',
                                                       'NH3_anthro_emi', 'SO2_anthro_emi', 'NO_anthro_emi', 'N2O_anthro_emi', #'OC_anthro_emi', 'BC_anthro_emi', 'NMVOC_anthro_emi',
                                                       #'DST_offline_emi', 'SSLT_offline_emi',
                                                       'PBLH', 'RH', 'T2M', 'U10M', 'V10M','PRECTOT',]
                                                       #'Crop_Nat_Vege_Mos', 'Permanent_Wetlands', 'Croplands', 'Urban_Builtup_Lands',
                                                       #'S1','S2','S3','elevation'] #  'Lat', 'Lon',


[Training-Settings.Loss-Functions]

Loss_type                                             = 'MSE'



