
#########################################################################################################################################################
[Pathway]

[Pathway.observations-dir]

ground_observation_data_dir  = '/my-projects/Projects/PM25_Speices_DL_2023/data/monthly_observation/' 
geophysical_species_data_dir = '/my-projects/Projects/PM25_Speices_DL_2023/data/monthly_geophysical/'
geophysical_biases_data_dir  = '/my-projects/Projects/PM25_Speices_DL_2023/data/monthly_biases/'

[Pathway.TrainingModule-dir]

training_infile = '/my-projects/Projects/PM25_Speices_DL_2023/data/TraningDatasets/NH4/NH4-cnn_TrainingData_44channels_11x11_200001-201912.nc'
model_outdir    = '/my-projects/Projects/PM25_Speices_DL_2023/code/Training_Evaluation_Estimation/'

[Pathway.Results-dir]

txt_outdir   = '/my-projects/Projects/PM25_Speices_DL_2023/code/Training_Evaluation_Estimation/'

[Pathway.Config-outdir]

Config_outdir = '/my-projects/Projects/PM25_Speices_DL_2023/code/Training_Evaluation_Estimation/'

[Pathway.Figures-dir]

Loss_Accuracy_outdir = '/my-projects/Projects/PM25_Speices_DL_2023/code/Training_Evaluation_Estimation/'
#########################################################################################################################################################
[Training-Settings]

[Training-Settings.identity]

version      = 'v0.0.0'
special_name = '_ResNet_Basic2222_NoMaxPooling_1'

[Training-Settings.hyper-parameters]

epoch         = 30
batchsize     = 512
learning_rate = 0.01

channel_names = ['EtaAOD_Bias', 'EtaCoastal', 'EtaMixing', 'EtaSGAOD_Bias', 'EtaSGTOPO_Bias', 'AOD', 'ETA', 'GeoPM25',
                     'GL_CNN_PM25',
                     'GC_PM25', 'GC_NH4', 'GC_SO4', 'GC_NIT', 'GC_SOA', 'GC_OC', 'GC_OM', 'GC_BC', 'GC_DST', 'GC_SSLT',
                     'NH3_anthro_emi', 'SO2_anthro_emi', 'NO_anthro_emi', 'N2O_anthro_emi', #'OC_anthro_emi', 'BC_anthro_emi', 'NMVOC_anthro_emi',
                     #'DST_offline_emi', 'SSLT_offline_emi',
                     'PBLH', 'RH', 'T2M', 'U10M', 'V10M','PRECTOT',
                     'Crop_Nat_Vege_Mos', 'Permanent_Wetlands', 'Croplands', 'Urban_Builtup_Lands',
                     'S1','S2','S3','elevation'] #  'Lat', 'Lon',


[Training-Settings.learning-objective]

species = 'NH4' # ['PM25', 'NH4', 'SO4', 'NO3', 'OM', 'BC', 'DUST', 'SS' ]
# Only one of these can be true. Default is bias.
bias = true   # learning objectives: bias = ground-based species observation - geophysical species concentration estimation
normalize_species = false
absolute_species  = false 
log_species = false


[Training-Settings.Loss-Functions]

Loss_type = 'MSE'



#########################################################################################################################################################

[Spatial-CrossValidation]

Spatial_CrossValidation_Switch      = false
Spatial_CV_LossAccuracy_plot_Switch = true

[Spatial-CrossValidation.Training_Settings]

kfold   = 10
repeats = 1
beginyears = [2000, 2005, 2010, 2015]
endyears   = [2004, 2009, 2014, 2019]

[Spatial-CrossValidation.Visualization_Settings]

regression_plot_switch = true

[Spatial-CrossValidation.Forced-Slope-Unity]

ForcedSlopeUnity = false # True: force the slope to unity and offset to zero with Training datasets
EachMonthForcedSlopeUnity = true # True: force the slope to unity and offset to zero by each year, each month; False: by each month, but all-year average 
